### DISCUSSION TITLE
GIF as Feature Image not displaying properly

### DISCUSSION THREAD

**Discussion by Sarund9** [pacollins/calligraphy#13] [Q&A]
I want to add a GIF as the Header in my Entry

Index.md Header:
```toml

title = "URP Shaders"
feature = "ShaderIntro.gif"

```

Left: GIF Opened in VSCode
Right: Website
![image](https://user-images.githubusercontent.com/53350334/216397390-d8067d6d-e8b8-46f5-911d-7fc2e6f4ce86.png)
